// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import SyntaxHighlightController from "./syntax_highlight_controller"
application.register("syntax-highlight", SyntaxHighlightController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)

import LessonListController from "./lesson_list_controller"
application.register("lesson-list", LessonListController)

import LessonCompleteController from "./lesson_complete_controller"
application.register("lesson-complete", LessonCompleteController)

