plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

inherit_gem:
  pundit: config/rubocop-rspec.yml

AllCops:
  TargetRailsVersion: 8.1
  TargetRubyVersion: 4.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'config/**/*.rb'

# It is legacy and will be removed in future versions of RSpec Rails
RSpecRails/InferredSpecType:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

RSpec/NestedGroups:
  Max: 4

Metrics/AbcSize:
  Max: 20
